version: "3"
services:
  flask:
    build: .
    # image: mrarmonius/flask_imc_cloud-tp
    ports:
      - "8080:5000"
    networks:
      - database_network
      - web_network
    depends_on:
        mysql_server:
          condition: service_healthy
        
  nginx:
    image: nginx
    volumes:
      - ./source/static:/usr/src/app/static:ro
      - ./nginx/tp_cloud.conf:/etc/nginx/conf.d/tp_cloud.conf
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web_network
    depends_on:
      flask:
        condition: service_started

  mysql_server:
    image: "mysql/mysql-server:latest"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=tp1_server"
      - "MYSQL_PASSWORD=your_password"
      - "MYSQL_DATABASE=tp1_cloud"
    volumes:
      - ./source/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - database_network
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
      timeout: 10s
      retries: 10
  
networks:
  database_network:
    driver: bridge
  web_network:
    driver: bridge
